spring.application.name=hubnapse

spring.datasource.url=jdbc:postgresql://localhost:5433/hubnapse
spring.datasource.username=hubnapse
spring.datasource.password=hubnapse
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}